# MPLAB IDE generated this makefile for use with GNU make.
# Project: power_control.mcp
# Date: Sat Jan 12 15:05:06 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

p10f202_lowpower_controller.cof : p10f202_lowpower_controller.o
	$(CC) /p10F202 "p10f202_lowpower_controller.o" /z__MPLAB_BUILD=1 /m"p10f202_lowpower_controller.map" /w /o"p10f202_lowpower_controller.cof" /x

p10f202_lowpower_controller.o : p10f202_lowpower_controller.asm ../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P10F202.INC
	$(AS) /q /p10F202 "p10f202_lowpower_controller.asm" /l"p10f202_lowpower_controller.lst" /e"p10f202_lowpower_controller.err" /c-

clean : 
	$(CC) "p10f202_lowpower_controller.o" "p10f202_lowpower_controller.hex" "p10f202_lowpower_controller.err" "p10f202_lowpower_controller.lst" "p10f202_lowpower_controller.cof" "p10f202_lowpower_controller.map"

